import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { PathWrapper } from "./path-wrapper";
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
    title: "Hedgeon Finance",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <SpeedInsights />
                    <PathWrapper>{children}</PathWrapper>
                </Providers>
            </body>
        </html>
    );
}
